### ISSUE TITLE
TODO List for 1.0 release!

### ISSUE THREAD

**Issue by matcracker** [matcracker/PocketMine-ManagerServers-Java#1]
This is a first list of things are work in progress in the project before the first release:
- [x] Add loader
- [x] Add installer.
- [x] Add downloader.
- [x]  Add manager.
- [x] Add editor.
- [x] Add editor properties.
- [x] Add editor performance.
- [x] Add opener.
- [x] Add backup/restore.
- [x] Add languages.
- [x] Add resetter.
- [x] Add informations.
- [x] Add dev mode
- [x] Implement APIs
- [x] Bug fix.
- [x] Testing all software.
