### ISSUE TITLE
TODO List for v1.1

### ISSUE THREAD

**Issue by matcracker** [matcracker/PocketMine-ManagerServers-Java#2]
Hello! It's time to create a new list for improve and add new cool things in the software!
- [x] Add to possibility to download PHP binaries.
- [x] Add command sending to servers.
- [x] Add server restarter.
- [x] Add commands for software (Developer Mode).
- [x] Add possibility for add/edit/delete path of server.
- [x] Create a new mode for install servers (for newest users).
- [x] Add possibility to select path for Server's OS.
- [x] Test all.
- [x] Bug fix.
